name: Daily AI Automation


on:

  schedule:

    # Every day 8 AM Bangladesh time
    - cron: "0 2 * * *"


  workflow_dispatch:



jobs:

  automation:

    runs-on: ubuntu-latest


    permissions:

      contents: write



    steps:


      - name: Checkout repository

        uses: actions/checkout@v4



      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.12"



      - name: Install packages

        run: |

          pip install google-generativeai



      - name: Run AI generator

        env:

          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

        run: |

          python automation/main.py



      - name: Create random commits

        run: |

          git config user.name "AI Daily Bot"

          git config user.email "ai-bot@github.com"



          for file in data/*.md

          do

            git add "$file"

            git commit -m "docs: AI developer update $(date +%H:%M:%S)" || true

            git push

            sleep 20

          done
